apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: application-service
  labels:
    app: transaction-microservice
spec:
  selector:
    app: transaction-microservice
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP